version: "3.7"

services:
  mysql:
    image: mysql:5.7.36
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql:rw
    networks:
      - default
  app:
    build:
      dockerfile: .build/dev/app/Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
    volumes:
      - ./src:/var/www/app:rw
      - ./.build/dev/app/conf/apache/apache2.conf:/etc/apache2/apache2.conf:ro
      - ./.build/dev/app/conf/apache/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./.build/dev/app/conf/php/php.ini:/usr/local/etc/php/php.ini:ro
    ports:
      - "8090:80"
    restart: "always"
    depends_on:
      - mysql
    networks:
      - default
  node:
    image: pk/node:16.13.0-alpine3.14
    build:
      context: .
      dockerfile: .build/dev/node/Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - TZ=${TZ}
    volumes:
      - ./src:/var/www/app:rw
    restart: "always"
    depends_on:
      - app
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - TZ=${TZ}
      - PMA_ARBITRARY=1
    ports:
      - "8091:80"
    restart: "always"
    depends_on:
      - mysql
    networks:
      - default
volumes:
  mysqldata:
networks:
  default:
    driver: bridge
    ipam:
      driver: default